Repository BrasilAPI/BrasilAPI, pull requests merged in 2020-12, with the labels that each got.

#168 Correção do fluxo de testes e CI
  .github/workflows/e2e-tests.yml
  jest.config.js
  package.json
  tests/cep-v1.test.js
  tests/ddd-v1.test.js
  tests/graphql-v1.test.js
  tests/helpers/server/index.js
  tests/helpers/server/setup.js
  tests/helpers/server/teardown.js
Labels: bug, enhancement

#85 Add banks routes
  README.md
  pages/api/banks/v1/[code].js
  pages/api/banks/v1/index.js
  services/banco-central.js
  tests/banks-v1.test.js
Labels: enhancement

#171 Adicionando página de documentação /docs
  README.md
  package-lock.json
  package.json
  pages/api/ddd/v1/[ddd].js
  pages/docs/doc.json
  pages/docs/index.js
Labels: documentation
