Repository BrasilAPI/BrasilAPI, pull requests merged in 2021-01, with the labels that each got.

#134 🖼 contributors embed image using hidden feature of github
  README.md
Labels: documentation

#170 docs: contributing guide refactored
  CONTRIBUTING.md
  README.md
Labels: documentation

#99 Ibge uf
  README.md
  pages/api/ibge/uf/v1/[code].js
  pages/api/ibge/uf/v1/index.js
  pages/docs/doc.json
  services/ibge.js
  tests/ibge-uf-v1.test.js
Labels: enhancement, feature request

#197 Corrige problemas listados pelo ESlint
  .gitignore
  package-lock.json
  package.json
  pages/api/ddd/v1/[ddd].js
  pages/index.js
Labels: documentation, enhancement

#191 add code of conduct proposal
  CODE_OF_CONDUCT.md
Labels: documentation

#174 issue #128 - Rota DDD não funciona retorna "DDD não existe" para DDDs válidos.
  README.md
  package.json
  pages/api/ddd/v1/[ddd].js
  pages/docs/doc.json
  services/ddd.js
  tests/ddd-v1.test.js
  tests/helpers/ddd/index.js
  tests/helpers/scenarios/ddd/incorrect.json
  tests/helpers/scenarios/ddd/inexistent.json
  tests/helpers/scenarios/ddd/success.json
Labels: bug

#206 fix(banco-central): add fallback to get bank list
  services/banco-central.js
  services/banco-central/banksList.json
  services/banco-central/index.js
Labels: bug, enhancement
