Repository BrasilAPI/BrasilAPI, pull requests merged in 2021-02, with the labels that each got.

#257 Atualização da lib de ceps
  package-lock.json
  package.json
  pages/api/cep/v1/[cep].js
  pages/docs/index.js
  tests/cep-v1.test.js
Labels: enhancement

#189 Update (NPM)
  CONTRIBUTING.md
Labels: documentation

#261 Correção pequena na definição das docs do CPNJ
  pages/docs/doc.json
Labels: bug
